development:
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: project_development
 pool: 5
 username: alice
 password: AwEs0Me!


test: &TEST
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: project_test
 pool: 5
 username: alice
 password: AwEs0Me!

production:
 adapter: postgresql
 encoding: utf8
 database: project_production
 pool: 5
 username: alice
 password: AwEs0Me!

cucumber:
  <<: *TEST