development:
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: project_development
 pool: 5
 username: pguser
 password: password


test: &TEST
 adapter: postgresql
 encoding: utf8
 host: localhost
 database: project_test
 pool: 5
 username: pguser
 password: password

production:
 adapter: postgresql
 encoding: utf8
 database: project_production
 pool: 5
 username: pguser
 password: password

cucumber:
  <<: *TEST